apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mynewapp
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ARGO-Deploy
    repoURL: 'https://github.com/gitbilla/argocd-k8.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
